version: '3.9'
services:

  webapp:
      container_name: loginwebapp
      image: loginwebapp
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - ./logs:/usr/local/tomcat/logs
      networks:
        - mynetwork
      restart: on-failure
      depends_on: 
        - postgres
  postgres:
      container_name: postgres_db
      image: postgres:11-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: "Admin@777"
        POSTGRES_DB: "sample"
        PGPORT: "5432"
        POSTGRES_USER: "Admin"
      restart: "on-failure"
      networks: 
        - mynetwork

networks: 
  mynetwork:
    driver: bridge